extends:
  # https://www.npmjs.com/package/eslint-config-airbnb-base
  - airbnb-base
  # https://www.npmjs.com/package/eslint-plugin-vue
  - plugin:vue/recommended

env:
  es6: true
  browser: true
  node: true

plugins:
  - vue

rules:
  # ECMAScript 6
  arrow-parens: "off"
