title:      Kristof Dewilde
description: Hello. This is my website. I hope you like it.

baseurl:    /website
markdown:   kramdown

permalink:  /blog/:year/:month/:day/:title

feed:
    path:   /blog/atom.xml
sass:
    style:  compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  