title:       Kristof Dewilde
description: Hello. This is my website. I hope you like it.

source:    ./
host:       0.0.0.0
port:       8282
encoding:   UTF-8
markdown:   kramdown

permalink:  /blog/:title
feed:
    path:   /blog/atom.xml

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - ".gitignore"
  - ".babelrc"
  - ".editorconfig"
  - ".eslintrc.yml"
  - ".stylelintrc"
  - "package.json"
  - "package-lock.json"
  - CNAME
  - bin/
  - assets/src
  - node_modules/
