name: CI/CD

on:
  push:
    paths:
    - 'src/*'
    - 'src/*/*'
    - 'src/*/*/*'
    - 'src/*/*/*/*'
    - 'src/*/*/*/*/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: install and lint
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
      run: |
        npm install
        npm audit
        npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: make production build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
      run: |
        chmod +x ./bin/prod.sh
        ./bin/prod.sh
