name: CI/CD

on:
  pull_request:
  push:
    paths:
    - 'assets/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codebase
      uses: actions/checkout@master
    - name: Install node
      uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Code quality check
      run: |
        npm install
        npm audit
        npm run lint
    - name: Make production build
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_ACCESS: ${{ secrets.GITHUB_ACCESS }}
      run: |
        # npm run build:vue
        chmod +x ./bin/push_build.sh
        ./bin/push_build.sh
