name: CI/CD

on:
  push:
    paths:
    - 'src/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: install and lint
      run: |
        npm install
        npm audit
        npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: make production build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ../..
        chmod +x ./bin/prod.sh
        ./bin/prod.sh
