name: CI/CD

on:
  pull_request:
  push:
    paths:
    - 'assets/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1.3
      with:
        node-version: 13.x
    - name: Code quality check
      run: |
        npm install
        npm run lint
        npm audit
    - name: Make production build
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_ACCESS: ${{ secrets.GITHUB_ACCESS }}
      run: |
        npm run clean && npm run build
        chmod +x ./bin/push_build.sh
        ./bin/push_build.sh
