name: quality checks

on:
  push:
    paths:
    - '*.js'
    - '*.vue'
    - '*.css'
    - '*.scss'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: install and lint
      run: |
        npm install
        npm audit
        npm run lint
